### ISSUE TITLE
Interactively prompt to request transfer if needed

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#114]
The current output says:

```
Failed to claim device, server said  { ok: false,
  errors: [ 'That belongs to someone else. To request a transfer add ?request_transfer=true to the URL.' ] }
```

We can prompt yes/No to request transfer, take it over if it is a Photon etc..

**Comment by towynlin** [comment]
:+1:

**Comment by towynlin** [comment]
:+1:

To add some more detail — Kenneth got this by doing `particle device add xxx` which uses the Core claiming process. For a Photon, soft AP is a better alternative, but the Core process will work with either device. In any case, for the Core claiming process (using either device), we should interactively prompt to initiate a transfer rather than throwing the error.
