### ISSUE TITLE
Particle CLI windows setup

### ISSUE THREAD

**Issue by jlkalberer** [spark/particle-cli#315]
When I go through a brand new `particle setup` on a windows machine I'm running into some issues in a few places.  

Anyways, I have my device connected via USB and in listening mode.  I go through all the steps, connect to the photon, and then have the photon start scanning (It just hangs here `Asking the Photon to scan for nearby Wi-Fi networks...`). I've also tried manually entering the SSID/PW and that failed (repeats `> Obtaining device information...`).  I'm not sure why this doesn't work but if I had to guess it's that the connection to the Photon on Windows 10 is flaky.

***

I've actually had this process succeed once but I can't reproduce it.  I really think that this is an issue with my machine/Windows 10 and connecting to the Photon during the SoftAP step.

***

I think the easiest/best solution would be to use the `particle serial wifi` setup flow instead of using `WifiManager` if serial detects a device connected via USB.  I feel like with older versions of the CLI (very old) it used to do this...?

**Comment by monkbroc** [comment]
Thanks for reporting this. I'll review the Windows setup flow..

It may help to do a `particle update` to the Photon. In older firmware the Photon had trouble connecting to some networks.

**Comment by jlkalberer** [comment]
I'm pretty sure it's on the latest firmware.  I've just been trying to test these setup flows.

I updated the Photon and still see the issue.

**Comment by m-mcgowan** [comment]
Similar to https://github.com/spark/particle-cli/issues/122

**Comment by m-mcgowan** [comment]
I'm working on the setup process, and I've seen a [firmware issue](https://github.com/spark/firmware/issues/1252) where the device didn't close the socket on the first connection, but does on subsequent connections.  

The CLI was using version 1.1.4 of `softap-setup`, which I don't believe has any timeouts. So, this combined with the firmware bug could cause a hang, but one that is intermittent, if the process is retried without resetting the device, since subsequent socket connections are properly closed. 

This PR #343 updates to the latest `softap-setup` version which includes timeout for sockets. It also includes a workaround for the firmware socket bug, making the behaviour consistent on first and subsequent device setups.
