### ISSUE TITLE
keys doctor (device id) is case sensitive?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#321]
Opening a ticket because I got a report that the keys doctor treats device-ids as case sensitive, maybe we should lowercase them before hitting the api / generating keys?

**Comment by ScruffR** [comment]
Yup, that was my report - but please don't just restrict that fix to `keys doctor`.

Any command that takes a device ID, an access token, a webhook ID or any other hex number should be case-insensitive.

IMHO #208 should not have been closed, since the workaroun there wasn't really addressing the issue but only providing a short-term workaround - and if this issue would now be limited to `keys doctor` only, it can be expected that a similar issue will pop up sooner or later again.

**Comment by ScruffR** [comment]
This issue keeps wasting time on multiple levels 😩 

https://community.particle.io/t/photon-setup-flashing-cyan-with-a-quick-red-burst-now-orange-burst-solved/12118/178

**Comment by m-mcgowan** [comment]
If we expect deviceIDs to be case insensitive, shouldn't this go in the API rather than pushing the burden to all clients?
