### ISSUE TITLE
[Proposal] Handle output logs

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#84]
This will help create a non-interactive CLI by changing the log level that the user wants to have displayed.

Two possible packages:
- https://github.com/winstonjs/winston
- https://github.com/npm/npmlog

Winston is cool and you can do more fancy stuff with transporting the logs to somewhere else which might be useful for CI/CD environment while npmlog is kinda simple, sleek and easy to handle.

**Comment by emilyrose** [comment]
I love winston myself, and you mention the ability to send logs elsewhere which might be useful for us too.

**Comment by joegoggins** [comment]
:+1: 

The key use case I'd love to accommodate regarding output, is the ability to get machine readable output via a flag. It would cool if it were a global flag that you could pass to sub-command.

 I've seen this done a couple of different ways for pre-dominantly human-facing tools: as JSON (chef's knife) or as CSV (terraform apply). Either approach would be great. 

Having this ability would create bliss in my world by allowing me to drop nasty `grep` or `sed` commands like `particle bla bla | grep "thing"` from my scripts (and replace them with less nasty, more robust stuff that uses machine formatted output) :)

**Comment by kennethlimcp** [comment]
I'm suggesting something like:

```

var debug = false;

var LOG = debug ? console.log.bind(console) : function () {};

LOG("yay to controlling debug messages");
```

From: http://stackoverflow.com/questions/7500811/how-do-i-disable-console-log-when-i-am-not-debugging

does this sound feasible?

**Comment by brycekahle** [comment]
Ideally we would have multiple log levels, so verbosity is not an on/off situation. We may also want the ability to pipe all the output to a file in case of an error, regardless of what the console verbosity level was. This is something `winston` or other logging modules can provide.

I've been holding on this because there isn't a good way to have a global verbosity argument at the moment. Tackling that first, would allow logging to be added.
